import Phone1 from "../assets/images/phone-1.svg";
import Phone2 from "../assets/images/phone-2.svg";
import Phone3 from "../assets/images/phone-3.svg";
import Phone4 from "../assets/images/phone-4.svg";

export const SAMPLE_PHONES_PRODUCTS_LIST = [
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "1213",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone2,
        name: "Redmi K20 Pro (Carbon Black, 128 GB)",
        currentPrice: "₹37,500",
        originalPrice: "₹39,999",
        discount: "7% Off",
        offer: "5% cashback",
        emi: "EMI starts @ ₹1356",
        id: "32434",
        availableColors: ["black", "blue"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Redmi",
    },
    {
        imageFile: Phone3,
        name: "Samsung Galaxy Note 10 Plus (Aura Glow, 512 GB)",
        currentPrice: "₹65,534",
        originalPrice: "₹79,999",
        discount: "20% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹5000",
        id: "121332343",
        availableColors: ["black", "silver"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone4,
        name: "Samsung Galaxy Note 10 Plus (Aura Black, 512 GB)",
        currentPrice: "₹45,000",
        originalPrice: "₹49,999",
        discount: "7% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹1356",
        id: "331213",
        availableColors: ["red", "yellow", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "4554",
        availableColors: ["yellow", "blue", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "121333",
        availableColors: ["white", "blue", "black", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone2,
        name: "Redmi K20 Pro (Carbon Black, 128 GB)",
        currentPrice: "₹37,500",
        originalPrice: "₹39,999",
        discount: "7% Off",
        offer: "5% cashback",
        emi: "EMI starts @ ₹1356",
        id: "3243434",
        availableColors: ["grey", "pink", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Redmi",
    },
    {
        imageFile: Phone3,
        name: "Samsung Galaxy Note 10 Plus (Aura Glow, 512 GB)",
        currentPrice: "₹65,534",
        originalPrice: "₹79,999",
        discount: "20% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹5000",
        id: "121332343",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone4,
        name: "Samsung Galaxy Note 10 Plus (Aura Black, 512 GB)",
        currentPrice: "₹45,000",
        originalPrice: "₹49,999",
        discount: "7% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹1356",
        id: "323231213",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "45523234",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "12123233",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone2,
        name: "Redmi K20 Pro (Carbon Black, 128 GB)",
        currentPrice: "₹37,500",
        originalPrice: "₹39,999",
        discount: "7% Off",
        offer: "5% cashback",
        emi: "EMI starts @ ₹1356",
        id: "32432334",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Redmi",
    },
    {
        imageFile: Phone3,
        name: "Samsung Galaxy Note 10 Plus (Aura Glow, 512 GB)",
        currentPrice: "₹65,534",
        originalPrice: "₹79,999",
        discount: "20% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹5000",
        id: "1213323232343",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone4,
        name: "Samsung Galaxy Note 10 Plus (Aura Black, 512 GB)",
        currentPrice: "₹45,000",
        originalPrice: "₹49,999",
        discount: "7% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹1356",
        id: "3313232213",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "45532234",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Samsung Galaxy S10 Plus (Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "132122323",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone2,
        name: "Redmi K20 Pro (Carbon Black, 128 GB)",
        currentPrice: "₹37,500",
        originalPrice: "₹39,999",
        discount: "7% Off",
        offer: "5% cashback",
        emi: "EMI starts @ ₹1356",
        id: "322323434",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Redmi",
    },
    {
        imageFile: Phone3,
        name: "Samsung Galaxy Note 10 Plus (Aura Glow, 512 GB)",
        currentPrice: "₹65,534",
        originalPrice: "₹79,999",
        discount: "20% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹5000",
        id: "121332332343",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone4,
        name: "Samsung Galaxy Note 10 Plus (Aura Black, 512 GB)",
        currentPrice: "₹45,000",
        originalPrice: "₹49,999",
        discount: "7% Off",
        offer: "4% cashback",
        emi: "EMI starts @ ₹1356",
        id: "33445451213",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "Samsung",
    },
    {
        imageFile: Phone1,
        name: "Oneplus 10R(Ceramic White, 1 TB)",
        currentPrice: "₹25,534",
        originalPrice: "₹29,999",
        discount: "16% Off",
        offer: "12% cashback",
        emi: "EMI starts @ ₹1356",
        id: "456654",
        availableColors: ["red", "blue", "golden", "green"],
        keyFeatures: [
            "Capacity 6 kg :Suitable for bachelors & couples",
            "Warranty: 4 years on product, 4 years on motor 800 rpm:",
            "Higher the spin speed, faster the drying time",
        ],
        brand: "One plus",
    },
];
